### PR TITLE
Image: add hugo

### PR DESCRIPTION
**Pull request by mattmoor**
:gift: This change add a new image for the Hugo package, including a `-dev` variant.

/kind feature

### Pre-review Checklist

- [x] **IMPORTANT: 'image-request' tag has been applied if this PR is adding any images, including new versions or variants**

#### For new image PRs only

If you have an apko.yaml file in this PR you need to follow this checklist, otherwise feel free to remove.
- [x] Include tests, sufficient enough that you would trust this image running in production.
- [x] The version included is the latest GA version of the software
- [x] The latest tag points to the newest stable version
- [x] There is a dev tag available that includes a shell and apk tools (by depending on 'wolfi-base')
- [x] The image runs as `nonroot` and GID/UID are set to 65532
- [x] ENTRYPOINT
  - [x] For applications/servers/utilities call main program with no arguments e.g. [redis-server]
- [ ] CMD:
  - [ ] For server applications give arguments to start in daemon mode (may be empty)
  - [ ] For utilities/tooling bring up help e.g. `–help`
  - [ ] For base images with a shell, call it e.g. [/bin/sh]
- [ ] Consider where and how the image deviates from popular alternatives. Is there a good reason and is it documented?
- [ ] Add annotations e.g:
```
annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/busybox/ # use the academy site here
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/bazel # use github here
```
- [x] Check if environment variables are needed e.g. to set data locations
- [x] Ensure the image responds to SIGTERM
  - [x] `docker kill $(docker run -d --rm cgr.dev/chainguard/nginx)`
- [ ] Documentation. Let's make this excellent. Include usage example.
- [ ] Error logs write to stderr and normal logs to stdout. DO NOT write to file.

### CODE REVIEW

**Review by kaniini — APPROVED** [review]

**Comment by kaniini** [comment]
Looks like you need `monopod readme`, but otherwise looks fine.

**Comment by mattmoor** [comment]
I'm going to play with another test that runs the Hugo quickstart, so something more meaningful is tested

**Comment by mattmoor** [comment]
It also looks like I'm missing `archs`

**Comment by mattmoor** [comment]
Ok, this is RFAL.  As an added bonus I found a bug with `git submodule` in our Wolfi image 😞

**Pull request merged**
