### PR TITLE
wait-for-it pkg suitable with other archs

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

sorry, I forgot to add these archs 

/cc @rawlingsj

### CODE REVIEW

**Comment by rawlingsj** [comment]
we need to wait until the related APKs are available for different architectures.  Right now what's merged is correct.  We are hoping to have `arm` soon though.

**Review by marcofranssen — APPROVED** [review]

**Comment by marcofranssen** [comment]
Waiting for ARM support https://github.com/philips-labs/helm-charts/pull/80/files

**Comment by dlorenc** [comment]
We should be able to get this in now :)

**Comment by imjasonh** [comment]
https://github.com/chainguard-images/images/pull/146 updated `wait-for-it` to build for aarch64. The other archs aren't supported by Wolfi yet, so we should just stick with these two for now.

**Pull request closed without merging**
