### PR TITLE
Do not run k8s tests on main push

### PR DESCRIPTION
**Pull request by jdolitsky**

### CODE REVIEW

**Comment by imjasonh** [comment]
Why not? 🤔

**Comment by jdolitsky** [comment]
> Why not?

Well, for starters they are currently failing (and we know it). So everytime we merge something, this check runs and creates a red X on the latest commit on the repo.

**Comment by dlorenc** [comment]
I did a bunch of debugging on why the test is failing and had the start of a fix - is there an issue open for that? i can dump my notes in there.

TLDR: The fluent-bit image we have works fine by itself, but when you deploy it inside the helm chart the helm chart overrides the default configuration at runtime, and the injected config doesn't work with our build configuration because we don't include all the optional dependencies.

**Comment by jdolitsky** [comment]
@dlorenc opened https://github.com/chainguard-images/images/issues/431

**Pull request closed without merging**
