### PR TITLE
chore(zookeeper): Allow java to be dropped in

### PR DESCRIPTION
**Pull request by EyeCantCU**
Needed for Java FIPS

### CODE REVIEW

**Review by developer-guy — APPROVED** [review]

**Comment by developer-guy** [comment]
are they included in the extra_packages already? 🤔

**Comment by developer-guy** [comment]
I checked that they are not so don't you think that we should include them in extra_packages?

**Comment by EyeCantCU** [comment]
> default = ["zookeeper", "zookeeper-bitnami-compat"], we should add `openjdk-17-jre` and `openjdk-17-default-jvm` here.

Shouldn't these be getting pulled in as package deps?

**Comment by jdolitsky** [comment]
As part of a Chainguard effort to reduce code duplication and provide higher quality images, we have stopped accepting pull requests for changes to images in this repository. Due to this, we are closing all pull requests today in order to start fresh.

If you think this pull request was closed in error, please feel free to re-open this pull request or open an issue and we will try to help you out. Thank you!

**Pull request closed without merging**
