### PR TITLE
Move ruby to use cmd not entrypoint and add test.

### PR DESCRIPTION
**Pull request by amouat**

### CODE REVIEW

**Comment by tuananh** [comment]
i like this change. it's least surprise when switching from the official ruby image.

**Comment by luhring** [comment]
@amouat Just double-checking about the test mentioned in the PR title

**Comment by amouat** [comment]
good point @luhring ! One sec...

**Comment by amouat** [comment]
The test does very little - just runs with irb and ruby with `--version`. It will pick up if the entrypoint is changed (unless something clever is done with a script).

**Review by luhring — APPROVED** [review]

**Review by jdolitsky — APPROVED** [review]

**Pull request merged**
