### PR TITLE
add new wolfi based nginx and change the default latest tag to point …

### PR DESCRIPTION
**Pull request by rawlingsj**
…to it

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>

### CODE REVIEW

**Comment by rawlingsj** [comment]
I don't think I've got this PR quite right yet, not 100% sure about the tags.  Also as it's changing the default latest nginx image to be wolfi based it would be good to get some eyes on it.

**Comment by jdolitsky** [comment]
Failure due to nginx not starting up properly due to permissions:
```
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
2023/01/19 23:22:43 [emerg] 8#8: unknown log format "main" in /etc/nginx/nginx.conf:41
nginx-smoketest-1674170563
```

**Review by jdolitsky — APPROVED** [review]
approving in advance, considering we can fix the paths stuff

**Comment by rawlingsj** [comment]
Not too sure yet whats changed as this was working and passing CI - looking into it

**Comment by rawlingsj** [comment]
The CI failure seems to be apko using the wrong nginx package from wolfi, the logs say
```
Jan 19 23:42:04.062 [INFO] [arch:x86_64] installing nginx (1.23.3-r0)
```
when it should be `1.23.3-r1`

**Comment by jdolitsky** [comment]
we just need to re-run CI, there was a regression in apko

**Pull request merged**
