### PR TITLE
Add cadvisor

### PR DESCRIPTION
**Pull request by Dentrax**
Fixes:

Related: To fix CVEs: https://github.com/wolfi-dev/os/pull/2923

### Pre-review Checklist

* CVE: Before: `119 packages, 97 vulnerabilities`, After: `94 packages, 6 vulnerabilities`
* `89.7MB` to `37.6MB`
* https://github.com/google/cadvisor/blob/master/deploy/Dockerfile

- [ ] **IMPORTANT: 'image-request' tag has been applied if this PR is adding any images, including new versions or variants**

#### Quality Requirements for Images PRs
The items in this checklist should all be checked in the PR with exceptions clearly documented.
The general idea is that to the extent possible, the image should be a drop-in replacement to its public counterpart.
- [X] Image is a smaller size than its common public counterpart, or if not, the reason why should be explained
- [X] Image should be scanned for CVEs and should return 0 or near-0 results. Exceptions should be explained.
- [X] The software in the image should be able to be installed and work as expected
  - [X] The image should start in a cluster
  - [X] The application should be accessible to the user/cluster/etc. as expected
- [ ] If there is an open source helm chart provided, the image should be able to be used with the chart. If needed, please add a -compat package to close any gaps with the public helm chart.
- [X] build for x86_64 and aarch64 if possible, document exceptions

#### For new image PRs only

If you have an apko.yaml file in this PR you need to follow this checklist, otherwise feel free to remove.
- [X] Include tests, sufficient enough that you would trust this image running in production.
- [X] Perform manual tests as needed and document your testing results
  - [ ] For builder images (go, python, etc), build a sample app successfully
  - [X] For services images (rabbit, databases, webservers) test basic functionality, upstream install/getting started, port availability, admin access. Document differences from public image.
  - [ ] Applications intended for use with a specific cloud provider must be tested on that cloud provider.

- [X] The version included is the latest GA version of the software
- [X] The latest tag points to the newest stable version
- [ ] There is a dev tag available that includes a shell and apk tools (by depending on 'wolfi-base')
- [ ] The image runs as `nonroot` and GID/UID are set to 65532 or upstream default
  - [ ] Alternatively the username and GID/UID may be a commonly used one from the ecosystem e.g: postgres
- [ ] The image contains the ca-certs bundle if needed
- [X] ENTRYPOINT
  - [X] For applications/servers/utilities call main program with no arguments e.g. [redis-server]
  - [ ] For base images leave empty
  - [ ] For dev variants set to entrypoint script that falls back to system
- [ ] CMD:
  - [ ] For server applications give arguments to start in daemon mode (may be empty)
  - [ ] For utilities/tooling bring up help e.g. `–help`
  - [ ] For base images with a shell, call it e.g. [/bin/sh]

- [X] Add annotations e.g:
```
annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/busybox/ # use the academy site here
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/bazel # use github here
```
- [X] Check if environment variables are needed e.g. to set data locations
- [X] Ensure the image responds to SIGTERM
  - [ ] `docker kill $(docker run -d --rm cgr.dev/chainguard/nginx)`
- [ ] Error logs write to stderr and normal logs to stdout. DO NOT write to file.
#### Documentation Requirements

- [X] Provide a README file, follow the [README template](readme-template.md) to include variants, tags, and usage examples
- [ ] Document your testing and results in the PR
- [ ] Document any exceptions to the testing and config requirements outlined in this template
- [ ] Document where and how the image deviates from popular alternatives (ports, packages, user, entrypoint, versions, etc). Explain why there's a difference and if the user needs to do anything differently when using the image

### CODE REVIEW

**Review by imjasonh — COMMENTED** [review]
This needs a rebase, and might be worth porting to TF if possible.

**Comment by michaelharrer** [comment]
Hey,

this could be really helpful for us. Do we have a due-date? :)

**Comment by dlorenc** [comment]
We can try to prioritize getting this one in! Can you share a bit more information about your use case?

**Comment by developer-guy** [comment]
now, all checks are passed, this image is ready for merge /cc @dlorenc 💜

**Review by kaniini — APPROVED** [review]

**Comment by michaelharrer** [comment]
Wow - thanks for the fast merge. 
Sorry that I didn’t give any details in time!

**Pull request merged**
