### PR TITLE
feat: add fluent-bit image

### PR DESCRIPTION
**Pull request by tuananh**
Signed-off-by: Tuan Anh Tran <me@tuananh.org>

Depends on https://github.com/wolfi-dev/os/pull/456

Related issue: https://github.com/wolfi-dev/os/issues/452

### CODE REVIEW

**Review by luhring — APPROVED** [review]

**Comment by patrick-stephens** [comment]
I touched on it in the package PR but wanted to check here: https://github.com/wolfi-dev/os/pull/456#issuecomment-1396855466

If there is no `/bin/sh` we should disable the `exec` plugin build otherwise it can silently fail in weird and wonderful ways behind the scenes.

**Comment by tuananh** [comment]
We can add busybox as runtime dep so that sh will be available?

**Comment by patrick-stephens** [comment]
> We can add busybox as runtime dep so that sh will be available?

Sure, it has to be `/bin/sh` - we have had issues with busybox installs putting the `sh` executable elsewhere which doesn't work. We can test it fairly easily though.

It depends if you want to use the same package as the OS or not though - adding a shell to an image may not be the desired option but I can't answer that for your project. We could also disable the `exec` plugin on the OS package to keep them consistent as an alternative but it can be a useful plugin particularly for consuming legacy logs.

**Comment by patrick-stephens** [comment]
FYI, the deltas been a shell-enabled image (in this case the UBI one we push to RHCC) and one without (the distroless one):

Shell:
```shell
$ docker run --rm -it ghcr.io/calyptia/fluent-bit:ubi9  -i exec -p 'command=echo hello' -o stdout
Fluent Bit v2.0.8
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/01/20 12:18:25] [ info] [fluent bit] version=2.0.8, commit=9444fdc5ee, pid=1
[2023/01/20 12:18:25] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/01/20 12:18:25] [ info] [cmetrics] version=0.5.8
[2023/01/20 12:18:25] [ info] [ctraces ] version=0.2.7
[2023/01/20 12:18:25] [ info] [input:exec:exec.0] initializing
[2023/01/20 12:18:25] [ info] [input:exec:exec.0] storage_strategy='memory' (memory only)
[2023/01/20 12:18:25] [ info] [output:stdout:stdout.0] worker #0 started
[2023/01/20 12:18:25] [ info] [sp] stream processor started
[0] exec.0: [1674217105.274420833, {"exec"=>"hello"}]
[0] exec.0: [1674217106.272490067, {"exec"=>"hello"}]
````

No shell:
```shell
$ docker run --rm -it fluent/fluent-bit  -i exec -p 'command=echo hello' -o stdout
Fluent Bit v2.0.8
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/01/20 12:18:47] [error] [config] section 'exec' tried to instance a plugin name that don't exists
[2023/01/20 12:18:47] [error] configuration file contains errors, aborting.
```

**Comment by tuananh** [comment]
let's do withotu the exec plugin for now. i already have `-DFLB_IN_EXEC=Off ` flag in in the build commadn so it should be good right?

**Comment by amouat** [comment]
busybox should install a shell to /bin/sh. It's a link to /bin/busybox, but that shouldn't matter.

**Comment by amouat** [comment]
If it's popular plug-in, we can also have a variant image with it enabled.

**Comment by tuananh** [comment]
> Sure, it has to be `/bin/sh` - we have had issues with busybox installs putting the `sh` executable elsewhere which doesn't work. We can test it fairly easily though.

i think if we use this syntax below, it's should be good no matter where `sh` is located right?


```sh
#!/usr/bin/env sh
```

**Comment by patrick-stephens** [comment]
> > Sure, it has to be `/bin/sh` - we have had issues with busybox installs putting the `sh` executable elsewhere which doesn't work. We can test it fairly easily though.
> 
> i think if we use this syntax below, it's should be good no matter where `sh` is located right?
> 
> ```shell
> #!/usr/bin/env sh
> ```

This is fine for a script but the issue is the popen syscall requires a /bin/sh link, it's nothing to do with a shell script or what you invoke but how you invoke it. At least that's what the underlying issue we have upstream documented.

**Review by jdolitsky — APPROVED** [review]

**Pull request merged**
