### PR TITLE
Add bash as default cmd.

### PR DESCRIPTION
**Pull request by amouat**
Update to make `docker run -it cgr.dev/chainguard/bash` work as expected.

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
i think makes sense

**Comment by amouat** [comment]
Thanks. I'll see if I can add some tests per @imjasonh's comments.

**Comment by amouat** [comment]
Added a really simple test just to make sure it doesn't error.

**Comment by amouat** [comment]
I converted to draft while we figure out how to handle https://github.com/chainguard-images/images/issues/923

**Pull request closed without merging**
