### PR TITLE
Add git to the ko image

### PR DESCRIPTION
**Pull request by rsrchboy**
Sometimes, when building projects that depend on private modules, go will attempt to invoke git to download those modules.  This causes Predictably Bad Things to happen:

    2023/10/19 21:45:46 Using base cgr.dev/chainguard/static:latest@sha256:ef5add7fd46cf1ce7d33d6de517833ac5c7e749db9b15249f9c472a772f3af27 for ..redacted...
    2023/10/19 21:45:47 Building ..redacted... for linux/s390x
    2023/10/19 21:45:47 Building ..redacted... for linux/386
    2023/10/19 21:45:47 Building ..redacted... for linux/arm/v7
    2023/10/19 21:45:47 Building ..redacted... for linux/amd64
    2023/10/19 21:46:17 Building ..redacted... for linux/arm64
    2023/10/19 21:46:17 Building ..redacted... for linux/arm/v6
    Error: failed to publish images: error building "ko://..redacted...": build: go build: exit status 1: go: downloading ...redacted... v1.2.3
    main.go:6:2: git init --bare in ...redacted.../go/pkg/mod/cache/vcs/698e3376d5ab1d9b02034561bf5649e96bda9b3ebabfda932ed4929dfa91b03c: exec: "git": executable file not found in $PATH

This change adds git to the list of packages to be included in the image build.

### Image Size

- [ ] The Image is smaller in size than its common public counterpart.
- [ ] The Image is larger in size than its common public counterpart (please explain in the notes).

Notes:

### Image Vulnerabilities

- [ ] The Grype vulnerability scan returned 0 CVE(s).
- [ ] The Grype vulnerability scan returned > 0 CVE(s) (please explain in the notes).

Notes:

### Basic Testing - K8s cluster

- [ ] The container image was successfully loaded into a kind cluster.
- [ ] The container image could not be loaded into a kind cluster (please explain in the notes).

Notes:

### Basic Testing - Package/Application

- [ ] The application is accessible to the user/cluster/etc. after start-up.
- [ ] The application is not accessible to the user/cluster/etc. after start-up. (please explain in the notes).

Notes:

### Helm

- [ ] A Helm chart has been provided and the container image can be used with the chart.  If needed, please add a -compat package to close any gaps with the public helm chart.
- [ ] A Helm chart has been provided and the container image is not working with the chart (please explain in the notes).
- [ ] A Helm chart was not provided.

Notes:

### Processor Architectures

- [ ] The image was built and tested for x86_64.
- [ ] The image could not be built for x86_64 (please explain in the notes).
- [ ] The image was built and tested for aarch64.
- [ ] The image could not be built for aarch64. (please explain in the notes).

Notes:

### Functional Testing + Documentation

- [ ] Functional tests have been included and the tests are passing.  All tests have been documnted in the notes section.

Notes:

### Environment Testing + Documentation

- [ ] There has not been a request and/or there is no indication that this image needs tested on a public cloud provider.
- [ ] The container image has been tested successfully on a public cloud provider (AWS, GCP, Azure).
- [ ] The container image has not been tested successfully on a public cloud provider (AWS, GCP, Azure) (please explain in the notes).

Notes:

### Version

- [ ] The package version is the latest version of the package.  The latest tag points to this version.
- [ ] The package version is the not the latest version of the package (please explain in the notes).

Notes:

### Dev Tag Availability

- [ ] There is a dev tag available that includes a shell and apk tools (by depending on 'wolfi-base')
- [ ] There is not a dev tag available that includes a shell and apk tools (by depending on 'wolfi-base') (please explain in the notes).

Notes:

### Access Control + Authentication

- [ ] The image runs as `nonroot` and GID/UID are set to 65532 or upstream default
- [ ] Alternatively the username and GID/UID may be a commonly used one from the ecosystem e.g: postgres
- [ ] The image requires a non-standard username or non-standard GID/UID (please explain in the notes).

### ENTRYPOINT

- [ ] applications/servers/utilities set to call main program with no arguments e.g. [redis-server]
- [ ] applications/servers/utilities not set to call main program with no arguments e.g. [redis-server] (please explain in the notes)
- [ ] base images leave empty.
- [ ] base image and not empty (please explain in the notes).
- [ ] dev variants is set to entrypoint script that falls back to system.
- [ ] dev variants is not set to entrypoint script that falls back to system (please explain in the notes).

### CMD

- [ ] For server applications give arguments to start in daemon mode (may be empty)
- [ ] For utilities/tooling bring up help e.g. `–help`
- [ ] For base images with a shell, call it e.g. [/bin/sh]

### Environment Variables

- [ ] Environment variables added.
- [ ] Environment variables not added and not required.

### SIGTERM

- [ ] The image responds to SIGTERM (e.g., `docker kill $(docker run -d --rm cgr.dev/chainguard/nginx)`)

### Logs

- [ ] Error logs write to stderr and normal logs to stdout. Logs DO NOT write to file.

### Documentation - README

- [ ] A README file has been provided and it follows the README template.

### CODE REVIEW

**Review by imjasonh — APPROVED** [review]

**Comment by imjasonh** [comment]
Sorry I didn't see this earlier! I refactored the ko image build recently which unfortunately caused a merge conflict for you. 😩

The change looks good, it may just need a rebase and conflict resolution to make progress.

Sorry for that

**Comment by rsrchboy** [comment]
*poke*  @imjasonh any chance of a re-review?

**Review by imjasonh — APPROVED** [review]

**Comment by rsrchboy** [comment]
Thanks! :)

**Comment by imjasonh** [comment]
> @imjasonh Is there anything else I need to do for the new image to be released? I've been checking since November, and AFAICT git still isn't present in the image.

You're right!

This is my fault, on two counts:

1. When I migrated the ko image to the config module pattern in https://github.com/chainguard-images/images/pull/1757 I removed any reference to the YAML file; the image is configured purely with HCL now. I should have deleted the YAML file in that change.
2. When I reviewed this PR, I didn't take into account (1), so editing the YAML file didn't do anything!

Sorry for the confusion, I'll send a PR to add git in a way that actually has an effect 😓

**Comment by imjasonh** [comment]
https://github.com/chainguard-images/images/pull/2088

**Pull request merged**
