### PR TITLE
Image: Add clang 15 image. 

### PR DESCRIPTION
**Pull request by patflynn**
Fixes: #407

### Pre-review Checklist

- [x] **IMPORTANT: 'image-request' tag has been applied if this PR is adding any images, including new versions or variants**

#### For new image PRs only

If you have an apko.yaml file in this PR you need to follow this checklist, otherwise feel free to remove.
- [x] Image is marked experimental or stable as appropriate
- [x] The version included is the latest GA version of the software
- [x] The latest tag points to the newest stable version
- [x] There is a dev tag available that includes a shell and apk tools (by depending on 'wolfi-base')
- [x] The image runs as `nonroot` and GID/UID are set to 65532
  - [ ] Alternatively the username and GID/UID may be a commonly used one from the ecosystem e.g: postgres
  - [ ] See above for exceptions to nonroot rule
- [x] ENTRYPOINT
  - [x] For applications/servers/utilities call main program with no arguments e.g. [redis-server]
  - [ ] For base images leave empty
  - [ ] For dev variants set to entrypoint script that falls back to system
- [x] CMD:
  - [ ] For server applications give arguments to start in daemon mode (may be empty)
  - [x] For utilities/tooling bring up help e.g. `–help`
  - [ ] For base images with a shell, call it e.g. [/bin/sh]
- [ ] Consider where and how the image deviates from popular alternatives. Is there a good reason and is it documented?
- [ ] Add annotations e.g:
```
annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/busybox/ # use the academy site here
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/bazel # use github here
```
- [ ] Check if environment variables are needed e.g. to set data locations
- [ ] Ensure the image responds to SIGTERM
  - [ ] `docker kill $(docker run -d --rm cgr.dev/chainguard/nginx)`
- [ ] Documentation. Let's make this excellent. Include usage example.
- [ ] Error logs write to stderr and normal logs to stdout. DO NOT write to file.
- [x] Include tests, at the very least a basic smoke test.

### CODE REVIEW

**Comment by patflynn** [comment]
@kaniini assigned to you for review because I have no idea what I'm doing.  

One question: is running as root the right thing here? or is there a better way?

**Review by jdolitsky — COMMENTED** [review]
do we want `clang-15:latest` or `clang:15`/ `clang:latest` ? This would be first image with a version number in it

**Comment by patflynn** [comment]
@jdolitsky  @kaniini  good question. I don't know much about that tool but since it's clang-15 in wolfi I assumed the version stream should be locked to the major.

**Comment by patflynn** [comment]
WRT to the 15 tag, I don't want to add that for now.

**Comment by jdolitsky** [comment]
postgres is a good example. image name just "postgres:latest", but we built using postgresql-15: https://github.com/chainguard-images/images/blob/main/images/postgres/configs/latest.apko.yaml#L11

**Review by jdolitsky — APPROVED** [review]

**Pull request merged**
