### PR TITLE
Update dotnet README

### PR DESCRIPTION
**Pull request by erikaheidi**
Update .NET image README with correct pulling instructions. This PR addresses issue reported by @ryryryano

### CODE REVIEW

**Comment by erikaheidi** [comment]
The CI is failing with the readme check, but when I run `monopod readme` here n othing happens - it actually changes a different readme (`images/doppler-kubernetes-operator/README.md`) so I am not sure what I am doing wrong here.

**Review by imjasonh — APPROVED** [review]

**Comment by imjasonh** [comment]
```
Found a total of 1 issue(s). Please run the following at the root of this repo to fix: "monopod readme"
```

I'm not sure what the issue is but the tool should fix it for you 🤞

**Comment by erikaheidi** [comment]
I updated monopod and was able to run the command, but it reverted the README to its original state. I think I am missing something @imjasonh 
cc @jamonation maybe I need to update some .tf file?

**Comment by jamonation** [comment]
> The CI is failing with the readme check, but when I run `monopod readme` here n othing happens - it actually changes a different readme (`images/doppler-kubernetes-operator/README.md`) so I am not sure what I am doing wrong here.

Ah sorry about this @erikaheidi - it isn't obvious, but there are only two places to edit here, the `metadata.yaml` `compatibility_notes` section that can be multi-line markdown, and then in between the `<!--body:start-->...<!--body:end-->` section in `README.md`.

I know you're trying to edit the Download this image part, but that will always get overwritten. I think the least worst option would be to add the details about the two different images to the `compatibility_notes` section here.

**Comment by jamonation** [comment]
@erikaheidi https://github.com/chainguard-images/images/pull/2325 is what you're after here I think?

**Comment by erikaheidi** [comment]
> @erikaheidi #2325 is what you're after here I think?

Ok, that works for now, but we'll need to find a way to overwrite the download section, because there is no such image (cgr.dev/chainguard/dotnet). And this is the first info that shows up in the docs. This will probably happen with other images that have the same structure - they were broken down with different names than their parent folder.

**Comment by erikaheidi** [comment]
Closing this since the proposed change won't pass CI, #2325 should be a temporary solution.

**Pull request closed without merging**
