### PR TITLE
kafka: add compat, add e2e test

### PR DESCRIPTION
**Pull request by imjasonh**
Depends on https://github.com/wolfi-dev/os/pull/3666

This also adds a test of the kafka image using `docker-compose`, which lets it graduate from experimental status 🎓

### CODE REVIEW

**Comment by imjasonh** [comment]
This will need https://github.com/wolfi-dev/os/pull/4284 to make progress.

**Comment by rawlingsj** [comment]
> This will need https://github.com/wolfi-dev/os/pull/4284 to make progress.

Has been merged now, we are having a few build issues ATM, once recovered I'll re-trigger the CI tests in this PR and see if we can merge and close related issues.

**Comment by denhamparry** [comment]
Could we get an update on this PR please 🙏

**Review by cjohannsen81 — APPROVED** [review]

**Review by denhamparry — APPROVED** [review]
LGTM

**Review by rawlingsj — APPROVED** [review]

**Pull request merged**
