### PR TITLE
chore(imagetest/helm): add logs to Helm output

### PR DESCRIPTION
**Pull request by stormqueen1990**
Include a command to list logs from the pods deployed by a Helm chart to the `tflib/imagetest/helm` scripts.

### CODE REVIEW

**Comment by joshrwolf** [comment]
I worry this is too much noise to always include. For some images, the pod logs are crazy. How about compromising with an opt in variable?

**Comment by stormqueen1990** [comment]
> I worry this is too much noise to always include. For some images, the pod logs are crazy. How about compromising with an opt in variable?

I updated it, but the issue now is how would we turn it on when running on CI?

**Review by joshrwolf — APPROVED** [review]

**Review by found-it — DISMISSED** [review]
One thing to note is this will shove logs into the `.diagnostic.detail` field. It doesn't look like there's a size restriction on the field but we'll certainly put that to the test

**Comment by stormqueen1990** [comment]
> One thing to note is this will shove logs into the `.diagnostic.detail` field. It doesn't look like there's a size restriction on the field but we'll certainly put that to the test

@found-it it shouldn't always print in CI though, this is more for local debugging. Is there another way that this could become more suitable?

**Pull request closed without merging**
