### PR TITLE
Expose JDK env vars

### PR DESCRIPTION
**Pull request by mattmoor**

### CODE REVIEW

**Review by stormqueen1990 — APPROVED** [review]

**Comment by mattmoor** [comment]
oh whoops, I screwed something up...

**Comment by mattmoor** [comment]
lol `s/modules/module/`

**Comment by stormqueen1990** [comment]
> oh whoops, I screwed something up...

and I full-on missed that 😅

**Review by stormqueen1990 — APPROVED** [review]

**Comment by mattmoor** [comment]
... missing `.block` too.

This passes a plan locally.

**Review by stormqueen1990 — APPROVED** [review]

**Comment by stormqueen1990** [comment]
> ... missing `.block` too.
> 
> This passes a plan locally.

I saw the module and missed the `.block` 🤦‍♀️

**Pull request merged**
